storage:
  relicpath: "relics/"
layers:
  -
    name: LayerOne
    offset: 50
    effects:
      -
        name: DizzyAscensionEffect
        strength: 1
        durationRemaining: 15
    sectionOffsets:
      - [0,0,36]
      - [2863,16,41]
      - [4271,0,41]
      - [5422,-1,41]
    sectionAreas:
      - [185,1,126,58]
    lootTable:
      chunkrange:
        topRight: [190, 0]
        bottomLeft: [124, 60]
      relics: ALL
  -
    name: LayerTwo
    offset: 40
    effects:
      -
        name: DizzyAscensionEffect
        strength: 2
        durationRemaining: 22
    sectionOffsets:
      - [1246,-65,24]
      - [-42,-70,37]
  -
    name: LayerThree
    offset: 30
    effects:
      -
        name: DizzyAscensionEffect
        strength: 5
        durationRemaining: 30
      -
        name: HallucinatingAscensionEffect
        strength: 4
        durationRemaining: 30
      -
        name: SoundAscensionEffect
        strength: 1
        durationRemaining: 30
        sounds:
          - ENTITY_ZOMBIE_AMBIENT
          - BLOCK_FIRE_AMBIENT
          - BLOCK_GRASS_STEP
          - ENTITY_ZOMBIE_STEP
    sectionOffsets:
      - [-42,-70,49]
      - [790,-70,49]
      - [1622,-70,49]
      - [2454,-70,49]
      - [3196,-70,49]
      - [4118,-70,49]
      - [4950,-70,0]
  -
    name: LayerFour
    offset: 25
    abyssDeathMessage: "{Player} died from ascending on the fourth layer!"
    effects:
      -
        name: DizzyAscensionEffect
        strength: 10
        durationRemaining: 30
      -
        name: BloodyAscensionEffect
        strength: 10
        durationRemaining: 30
      -
        name: DamagingAscensionEffect
        strength: 4
        durationRemaining: 30
  -
    name: LayerFive
    offset: 20
    abyssDeathMessage: "{Player} died from ascending on the fifth layer!"
    effects:
      -
        name: DizzyAscensionEffect
        strength: 10
        durationRemaining: 30
      -
        name: BloodyAscensionEffect
        strength: 10
        durationRemaining: 30
      -
        name: DamagingAscensionEffect
        strength: 6
        durationRemaining: 30

  -
    name: LayerSix
    offset: 10
    abyssDeathMessage: "{Player} died from ascending on the sixth layer!"
    effects:
      -
        name: DeathAscensionEffect
        strength: 10
        durationRemaining: 30