layers:
  -
    name: LayerOne
    offset: 50
    effects:
      -
        name: DizzyAscensionEffect
        strength: 1
        duration: 15
  -
    name: LayerTwo
    offset: 40
    effects:
      -
        name: DizzyAscensionEffect
        strength: 2
        duration: 22
  -
    name: LayerThree
    offset: 30
    effects:
      -
        name: DizzyAscensionEffect
        strength: 5
        duration: 30
      -
        name: HallucinatingAscensionEffect
        strength: 4
        duration: 30
      -
        name: SoundAscensionEffect
        strength: 1
        duration: 30
        sounds:
          - ENTITY_ZOMBIE_AMBIENT
          - BLOCK_FIRE_AMBIENT
          - BLOCK_GRASS_STEP
          - ENTITY_ZOMBIE_STEP
  -
    name: LayerFour
    offset: 25
    abyssDeathMessage: "{Player} died from ascending on the fourth layer!"
    effects:
      -
        name: DizzyAscensionEffect
        strength: 10
        duration: 30
      -
        name: BloodyAscensionEffect
        strength: 10
        duration: 30
      -
        name: DamagingAscensionEffect
        strength: 4
        duration: 30
  -
    name: LayerFive
    offset: 20
    abyssDeathMessage: "{Player} died from ascending on the fifth layer!"
    effects:
      -
        name: DizzyAscensionEffect
        strength: 10
        duration: 30
      -
        name: BloodyAscensionEffect
        strength: 10
        duration: 30
      -
        name: DamagingAscensionEffect
        strength: 6
        duration: 30

  -
    name: LayerSix
    offset: 10
    abyssDeathMessage: "{Player} died from ascending on the sixth layer!"
    effects:
      -
        name: DeathAscensionEffect
        strength: 10
        duration: 30